services:

    word_of_the_day_generator:
        class: AppBundle\Command\WordOfTheDayGenerator
        arguments: ["@doctrine"]

    word_of_the_day_generator_command:
        class: AppBundle\Command\WordOfTheDayGeneratorCommand
        arguments: ["@word_of_the_day_generator"]
        tags:
            -  { name: console.command }

    term_alteration_listener:
        class: AppBundle\EventListener\TermAlterationListener
        arguments: ["@doctrine", "@admin_notifier", "@request_stack", "@session"]
        tags:
            - { name: kernel.event_listener, event: term_alteration, method: onTermAlteration }

    admin_notifier:
        class: AppBundle\Mailer\AdminNotifier
        arguments: ["@mailer", "@templating"]