<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermRepository extends EntityRepository
{

    public function findAllWithCategory()
    {
        $qb = $this->createQueryBuilder("t")
                ->select("t", "c")
                ->leftJoin("t.category", "c")
                ->addOrderBy("t.name", "ASC");

        return $qb->getQuery()->getResult();
    }

    public function findAllQualityWordIds()
    {
        $qb = $this->createQueryBuilder("t")
            ->select("t.id")
            ->leftJoin("t.examples", "e")
            ->groupBy("t")
            ->having("COUNT(e) > 0");
        $query = $qb->getQuery();

        $arrayResult = $query->getScalarResult();
        return $arrayResult;
    }


}
