<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermVoteRepository extends EntityRepository
{

    /**
     * Find a vote based on ip and Term
     *
     * @param $ip
     * @param Term $term
     * @return null|object
     */
    public function findExisting($ip, Term $term)
    {
        return $this->findOneBy(array(
            "ip" => $ip,
            "term" => $term
        ));
    }
}
