<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermVoteRepository extends EntityRepository
{

    public function findExisting($ip, $term)
    {
        return $this->findOneBy(array(
            "ip" => $ip,
            "term" => $term
        ));
    }
}
