<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\WordOfTheDay;

/**
 * WordOfTheDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordOfTheDayRepository extends EntityRepository
{

    /**
     * find the word of the day to display today
     *
     * @return null|WordOfTheDay
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findTodaysWord()
    {
        $qb = $this->createQueryBuilder("w")
                ->select("w", "t", "d")
                ->leftJoin("w.term", "t")
                ->leftJoin("t.definitions", "d")
                ->where("w.date = CURRENT_DATE()");
        $wotd = $qb->getQuery()->getOneOrNullResult();
        return $wotd;
    }
}
